#! /usr/bin/env python

#  ====  Chi3_util ===
# 
#  Creator: Myrta Gruning
#  Created: 05/07/13
#
#  For cubic material! 
#  Orientation field 100 and 110 
#  Read from YPP outputs o-YPP.X_probe_order_3* 
#  and calculates |X(1111)| and 3|X(1212)| and the module and phase of anysotropy
#  see  PHYSICAL REVIEW B, 41 1542
#  use: python YPPOutputFile_100 YPPOutputFile_110
#
import sys
import math
import time
#import numpy as np
from datetime import date
#
# I/O
#
filein1 = str(sys.argv[1])
filein2 = str(sys.argv[2])
fileout = filein1.replace("X_probe_order_3","Chi3_cubic")
i1=open(filein1,'r')
i2=open(filein2,'r')
of=open(fileout,'w')
is1=i1.readline()
is2=i2.readline()
#
# DEF FUNCTIONS
#
def scan_header(f):
 	i=f.readline()
 	while i.startswith('#'):
 		i=f.readline()
 	return i
#	
def Find_B(r1,r2,i1,i2):
	r = r2*2.*math.sqrt(2)-r1
	i = i2*2.*math.sqrt(2)-i1
        return r,i
def Module(Re,Im):
        return math.sqrt(Re*Re+Im*Im)
def Phase(Re,Im):
	return math.atan2(Im,Re)
def Complex_to_Polar_Form(Re,Im):
	Mod= Module(Re,Im)
	Ph = Phase(Re,Im)
	return Mod,Ph
def Divide_complex_in_polar_form(m1,p1,m2,p2):
	m = m1/m2
	p = p1-p2
	return m,p
#
# SCAN HEADERS
#
is1=scan_header(i1)
is2=scan_header(i2)
#
# READ, CALCULATE,WRITE
#
today=date.today()
ostring="# Generated by Chi3_util on "+str(today.day)+"/"+str(today.month)+"/"+str(today.year)+"\n"
ostring=ostring+"# by reading ypp files:"+ filein1+" and "+filein2+'\n'
ostring=ostring+"# E(eV)"+'\t'+"Im(A)"+'\t'+"Re(A)"+'\t'+"|A|"+'\t'+"Im(B)"+'\t'+"Re(B)"+'\t'+"|B|"+'\t'+"|B/A-1|"+'\t'+"atan(B/A)"+'\n'
of.write(ostring)
while (not is1.startswith('#') and not is2.startswith('#')):
    	t1=is1.split()
    	t2=is2.split()
	E=float(t1[0])
	ImA=float(t1[1])
	ReA=float(t1[2])
	ImC=float(t2[1])
	ReC=float(t2[2])
	ReB,ImB = Find_B(ReA,ReC,ImA,ImC)
	mA,pA = Complex_to_Polar_Form(ReA,ImA) 
	mB,pB = Complex_to_Polar_Form(ReB,ImB)
	mD,pD = Complex_to_Polar_Form(ReB-ReA,ImB-ImA)
	mS,pS=Divide_complex_in_polar_form(mD,pD,mA,pA)
        ostring=str(E)+'\t'+str(ImA)+'\t'+str(ReA)+'\t'+str(mA)+'\t'+str(ImB)+'\t'+str(ReB)+'\t'+str(mB)+'\t'+str(mS)+'\t'+str(pS)+'\n'
        of.write(ostring)
    	is1=i1.readline()
    	is2=i2.readline()
